version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing dependencies...
      - yum install -y maven
  build:
    commands:
      - echo Building JAR file...
      - mvn package
artifacts:
  files:
    - target/*.jar
    - install.sh
    - appspec.yml
